title: Joey's Blog
author: JoeyTeng
email: joey.teng.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of personal learning, experiences and thoughts.
  Ranging from Computer Science, Natural Science, Mathematics to Traveling, Photography and Videography.

# Social links
github_username: JoeyTeng

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect

url: "https://joeyteng.github.io"
plugins:
  - jekyll-sitemap
