title: Joey's Blog
author: JoeyTeng
email: joey.teng.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of personal learning, experiences and thoughts.
  Ranging from Computer Science, Natural Science, Mathematics to Traveling, Photography and Videography.

# Sidebar settings
sidebar: true


# Social links
github_username: JoeyTeng

show_excerpts: true # set to false to remove excerpts on the homepage

# Analytics settings
# Google Analytics
ga_track_id: 'UA-140346236-1'
ga_domain: auto
# Baidu Analytics
ba_track_id: e821c719bf561d4e6c0c6e5e49769883

theme: jekyll-theme-architect

url: "https://joeyteng.github.io"
plugins:
  - jekyll-sitemap
